import { collection, getDocs } from "firebase/firestore";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Header from "../components/Header/Header";
import { db } from "../lib/clientApp";
import { query, limit } from "firebase/firestore";
import styles from "../styles/index.module.css";

import mapboxgl from "mapbox-gl";

mapboxgl.accessToken =
  "pk.eyJ1IjoiaW51aXl1a2kwOTA0IiwiYSI6ImNsOWlmZXozbTBiNG4zdm1yZHoydWRra2oifQ.92mwSImqwWlQK5_-aIm6rg";

const Home = (props) => {
  const { data } = props;

  const mapContainer = useRef(null);
  const map = useRef(null);

  const createMarkerElement = (shop) => {
    let el = document.createElement("div");
    let img = document.createElement("img");

    // if (shop.id == "エネオス") {
    img.src = "/coffee-pink.png";
    // }
    img.className = styles["pin-img"];

    el.appendChild(img);

    let ptag = document.createElement("p");

    ptag.textContent = shop.brand_price;
    ptag.setAttribute("class", styles["brand-price"]);
    el.appendChild(ptag);

    return el;
  };

  const createPopupHTML = (shop) => {
    let brand;
    if (shop.brand_name == "エネオス") {
      brand = "/coffee-pink.png";
    }

    const html = `
      <div class="map-infowindow"> 
      <div class="info-header maker-'${shop.brand_name}'"></div>
      <div class="shop-title">
      <img src='${brand}' width="32px" height="32px" />
      <p class="shop-name"><a target="_blank" href="${shop.url}">
      ${shop.store_name} 
      </a></p></div>
      <div class="opentime">
        <p>${shop.open_time}</p>
      </div>
      <div class="prices">
        <div>
          <p class="price-popup">¥${shop.brand_price}</p>
        </div>
      </div>
      </div>`;

    return html;
  };

  const didEffect = useRef(false);
  useEffect(() => {
    if (!didEffect.current) {
      didEffect.current = true;

      if (map.current) return;
      data.map((shop) => {
        map.current = new mapboxgl.Map({
          container: mapContainer.current,
          style: "mapbox://styles/mapbox/streets-v11",
          center: shop.longlat,
          zoom: 9,
        });
        const el = createMarkerElement(shop);
        new mapboxgl.Marker(el)
          .setLngLat(shop.longlat)
          .setPopup(
            new mapboxgl.Popup({ offset: [0, -40] }).setHTML(
              createPopupHTML(shop)
            )
          ) // sets a popup on this marker
          .addTo(map.current);
      });
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>A Cup of Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coffee-pink.png" />
      </Head>
      <div className={styles.map} ref={mapContainer}></div>
    </div>
  );
};

export const getServerSideProps = async () => {
  const ref = collection(db, "stores");
  const Docs = await getDocs(query(ref, limit(1)));
  const data = Docs.docs.map((doc) => doc.data());
  const sliceData = data.slice(0, 1);

  const aa = sliceData.map((shop) => {
    return {
      store_name: "ドトールコーヒーショップ 川崎医科大学附属病院店",
      brand_name: "エネオス",
      address: "東京都渋谷区渋谷1-1-1",
      open_time: "月～金 7:00～20:00",
      brand_item: "カフェラテ",
      phone_number: "03-1234-5678",
      brand_price: 350,
      longlat: [139.767125, 35.681236],
    };
  });
  return {
    props: {
      data: aa,
    },
  };
};

export default Home;
