import { collection, getDocs } from "firebase/firestore";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Header from "../components/Header/Header";
import { db } from "../lib/clientApp";
import styles from "../styles/index.module.css";

const Home = (props) => {
  const { data } = props;
  const [shops, setShops] = useState([
    {
      branch: "no data",
      buiding: "no data",
      city: "no data",
      prefecture: "no data",
      storename: "no data",
      streetnum: "no data",
    },
  ]);

  const didEffect = useRef(false);
  // 初回レンダリング時だけ実装
  useEffect(() => {
    if (!didEffect.current) {
      didEffect.current = true;
      data.map((shop) => {
        setShops((prev) => [...prev, shop]);
      });
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>A Cup of Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ~/components/Header.jsxを編集することで表示を変えられる */}
      <Header />
      <div className={styles["card--container"]}>
        {/* 配列をmapで回して一個づつ表示 */}
        {shops.map((shop, idx) => (
          // style={{???}}とclassName={styles.???}は同じ意味!
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              border: "1px solid var(--pink1)",
              width: "100%",
              margin: "1rem",
              padding: "1rem",
            }}
            key={idx}
          >
            <p>{shop.storename}</p>
            <p>{shop.city}</p>
            <p>{shop.prefecture}</p>
            <p>{shop.branch}</p>
            <p>{shop.streetnum}</p>
            <p>{shop.buiding}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  const ref = collection(db, "shops");
  // firestoreからデータを取得
  const Docs = await getDocs(ref);
  const data = Docs.docs.map((doc) => doc.data());
  // とりあえず20件だけ表示する
  const sliceData = data.slice(0, 19);
  return {
    props: {
      data: sliceData,
    },
  };
};

export default Home;
